general.import = [
  # uncomment the flavour you want below: source https://github.com/catppuccin/alacritty
  # "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"

# Window settings
[window]
decorations = "full"  # Options: full, none, transparent, buttonless
opacity = 0.9        # Window opacity (0.0 to 1.0)
padding = { x = 10, y = 10 }  # Padding around the terminal content

# Font settings
[font]
normal = { family = "Fira Code", size = 12.0 }
bold = { family = "Fira Code", size = 12.0, style = "Bold" }
italic = { family = "Fira Code", size = 12.0, style = "Italic" }
bold_italic = { family = "Fira Code", size = 12.0, style = "Bold Italic" }

# Scrollback buffer
[scrolling]
history = 10000  # Number of lines to keep in the scrollback buffer
multiplier = 3   # Scroll speed multiplier

