# Thunderbird Mail espanso configuration file
# See docs https://espanso.org/docs/configuration/app-specific-configurations/

filter_class: "thunderbird"
backend: Inject
backspace_delay: 3
includes:
  - "../match/base.yml"
